//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quote_calculation_Application
{
    using System;
    using System.Collections.Generic;
    
    public partial class Insuree
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public int CarYear { get; set; }
        public string CarMake { get; set; }
        public string CarModel { get; set; }
        public Nullable<int> SpeedingTickets { get; set; }
        public Nullable<bool> HasDUI { get; set; }
        public Nullable<bool> IsFullCoverage { get; set; }
        public Nullable<decimal> QuoteAmount { get; set; }
    }
}
